Problem 1:

Write a Python/NumPy code block that finds the distinct/unique common items between these two
arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.

In [ ]:
import numpy as np
import pandas as pd

a1 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b1 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
common = np.intersect1d(a1, b1)
print("Common elements:", common)

Common elements: [2 4]


Problem 2:

Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
so that you do not need to explicitly key in every integer value.
1   6    11
2   7    12
3   8    13
4   9    14
5   10  15

In [ ]:
arr2 = np.arange(1, 16).reshape(5, 3, order='F')
print("\n5x3 array:\n", arr2)


5x3 array:
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


Problem 3:

The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

In [ ]:
flat_arr3 = arr2.flatten(order='F')
print("\nFlattened array:", flat_arr3)


Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Problem 4:

Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and the third column becomes the third dimension of the 3-D array.

In [ ]:
arr4 = np.moveaxis(arr2, 1, 0)
print("Transformed 3D array:\n", arr4)

Transformed 3D array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Problem 5:

Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.

In [ ]:
arr5 = np.moveaxis(arr4, 0, 1)
print("\nBack to 2D:\n", arr5)


Back to 2D:
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


Problem 6:

You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
Write a Python/Numpy code block that removes from array a any items that are also present in array b.

In [ ]:
a6 = np.array([12, 5, 7, 15, 3, 1, 8])
b6 = np.array([14, 6, 3, 11, 19, 12, 5])

new_a6 = np.setdiff1d(a6, b6)

print("a6 - elements also in b6:", new_a6)

a6 - elements also in b6: [ 1  7  8 15]


Problem 7:

Answer the following questions about the accompanying data file.

What is the maximum yearly NYC consumption of water in millions of gallons per day?
How many calendar years are represented within this data set? NumPy's shape command is one way to find
out.
What is the mean and the standard deviation of the per capita daily water consumption?
What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [ ]:
df = pd.read_excel('Module6_Data.xlsx', )

max_consumption = df["NYC Consumption(Million gallons per day)"].max()
print("\nMax yearly water consumption:", max_consumption)

num_years = df.shape[0]
print("Number of calendar years:", num_years)

mean_per_capita = df["Per Capita(Gallons per person per day)"].mean()
std_per_capita = df["Per Capita(Gallons per person per day)"].std()
print("Mean per capita:", mean_per_capita)
print("Standard Deviation per capita:", std_per_capita)

pop_diff = np.diff(df["New York City Population"])
print("Yearly population differences:\n", pop_diff)


Max yearly water consumption: 1512.0
Number of calendar years: 39
Mean per capita: 160.30769230769232
Standard Deviation per capita: 31.930973122258784
Yearly population differences:
 [-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
